CREATE TABLE PRODUCTS
(
    ID           BIGINT PRIMARY KEY NOT NULL,
    IMG          VARCHAR(220),
    PRODUCT_NAME VARCHAR(300) UNIQUE,
    DESCRIPTION  VARCHAR(500),
    PRICE        INTEGER,
    QUANTITY     INTEGER,
    CREATIONDATE DATE,
    CATEGORES_ID BIGINT REFERENCES CATEGORES(ID)
);

CREATE TABLE CATEGORES
(
    ID            BIGINT PRIMARY KEY NOT NULL,
    CATEGORY_NAME VARCHAR(300) UNIQUE,
    DESCRIPTION   VARCHAR(500),
    CREATIONDATE  DATE,
    PRODUCTS_ID   BIGINT REFERENCES PRODUCTS (ID)
);

CREATE TABLE PRODUCT_CATEGORY
(
    ID               BIGINT PRIMARY KEY NOT NULL,
    PRODUCTS_ID       BIGINT REFERENCES PRODUCTS (ID),
    CATEGORES_ID      BIGINT REFERENCES CATEGORES (ID)
);

CREATE TABLE USR
(
    ID       VARCHAR(300) PRIMARY KEY NOT NULL,
    USR_NAME VARCHAR(256),
    USERPIC  VARCHAR(256),
    EMAIL    VARCHAR(256),
    GENDER   VARCHAR(256),
    LOCALE   VARCHAR(256)
);

CREATE TABLE SPRING_SESSION
(
    PRIMARY_ID            CHAR(36) NOT NULL
        CONSTRAINT SPRING_SESSION_PK
            PRIMARY KEY,
    SESSION_ID            CHAR(36) NOT NULL,
    CREATION_TIME         BIGINT   NOT NULL,
    LAST_ACCESS_TIME      BIGINT   NOT NULL,
    MAX_INACTIVE_INTERVAL INTEGER  NOT NULL,
    EXPIRY_TIME           BIGINT   NOT NULL,
    PRINCIPAL_NAME        VARCHAR(300)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1
    ON SPRING_SESSION (SESSION_ID);

CREATE INDEX SPRING_SESSION_IX2
    ON SPRING_SESSION (EXPIRY_TIME);

CREATE INDEX SPRING_SESSION_IX3
    ON SPRING_SESSION (PRINCIPAL_NAME);


CREATE TABLE SPRING_SESSION_ATTRIBUTES
(
    SESSION_PRIMARY_ID CHAR(36)     NOT NULL
        CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK
            REFERENCES SPRING_SESSION
            ON DELETE CASCADE,
    ATTRIBUTE_NAME     VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES    BYTEA        NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK
        PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
);


